### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by baff3r** [Wykt/tiktok-viewbot#2]
`Exception in thread Thread-1 (title_daemon):
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/data/data/com.termux/files/home/tiktok-viewbot/viewbot.py", line 38, in title_daemon
    ctypes.windll.kernel32.SetConsoleTitleW("Tiktok View Bot | Views: " + str(count) + " | VPM: " + str(calculate_cpm()) + " | VPS: " + str(calculate_cpm_s()))
AttributeError: module 'ctypes' has no attribute 'windll'`

**Comment by Wykt** [comment]
It's patched anyways
